import type { YoutubeApiKey } from "@/api/apiKey.js";
import type {
  TranscriptMetadata,
  YouTubeApiCaptionItem,
  YouTubeApiResponse,
} from "@/api/types.js";
import { fetchApi } from "@/api/fetcher.js";
import { getTranscriptMetadata } from "@/api/transcripts/index.js";
import { err, ok } from "neverthrow";
import { beforeEach, describe, expect, test, vi } from "vitest";

// fetchApiをモック化
vi.mock("@/api/fetcher.js", () => ({
  fetchApi: vi.fn(),
}));

const mockFetchApi = vi.mocked(fetchApi);
const mockApiKey = "test-api-key" as YoutubeApiKey;

describe("transcripts API", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("getTranscriptMetadata", () => {
    const mockTranscriptResponse: YouTubeApiResponse<YouTubeApiCaptionItem> = {
      kind: "youtube#captionListResponse",
      etag: "test-etag",
      items: [
        {
          kind: "youtube#caption",
          etag: "caption-etag",
          id: "caption-id-1",
          snippet: {
            videoId: "test-video-id",
            language: "ja",
            name: "Japanese",
            audioTrackType: "primary",
            isCC: false,
            isLarge: false,
            isEasyReader: false,
            isDraft: false,
            isAutoSynced: false,
            trackKind: "standard",
          },
        },
        {
          kind: "youtube#caption",
          etag: "caption-etag-2",
          id: "caption-id-2",
          snippet: {
            videoId: "test-video-id",
            language: "en",
            name: "English",
            audioTrackType: "primary",
            isCC: false,
            isLarge: false,
            isEasyReader: false,
            isDraft: false,
            isAutoSynced: true,
            trackKind: "standard",
          },
        },
      ],
    };

    test("正常系: 字幕メタデータを取得する", async () => {
      mockFetchApi.mockResolvedValueOnce(ok(mockTranscriptResponse));

      const result = await getTranscriptMetadata("test-video-id", mockApiKey);

      expect(result.isOk()).toBe(true);
      expect(result.isErr()).toBe(false);
      expect(result._unsafeUnwrap()).toStrictEqual([
        {
          language: "ja",
          name: "Japanese",
          isAutoGenerated: false,
        } satisfies TranscriptMetadata,
        {
          language: "en",
          name: "English",
          isAutoGenerated: true,
        } satisfies TranscriptMetadata,
      ]);
      expect(mockFetchApi).toHaveBeenCalledWith(
        "captions",
        { videoId: "test-video-id", part: "snippet" },
        mockApiKey,
      );
    });

    test("正常系: 字幕データが部分的に欠けている場合にデフォルト値でマップされる", async () => {
      const incompleteResponse: YouTubeApiResponse<YouTubeApiCaptionItem> = {
        kind: "youtube#captionListResponse",
        etag: "test-etag",
        items: [
          {
            kind: "youtube#caption",
            etag: "caption-etag",
            id: "caption-id-incomplete",
            snippet: {
              videoId: "test-video-id",
              language: "fr",
            },
          },
        ],
      };

      mockFetchApi.mockResolvedValueOnce(ok(incompleteResponse));

      const result = await getTranscriptMetadata("test-video-id", mockApiKey);

      expect(result.isOk()).toBe(true);
      expect(result.isErr()).toBe(false);
      expect(result._unsafeUnwrap()).toStrictEqual([
        {
          language: "fr",
          name: "",
          isAutoGenerated: false,
        } satisfies TranscriptMetadata,
      ]);
    });

    test("正常系: 字幕が利用できない場合は空配列を返す", async () => {
      const emptyResponse: YouTubeApiResponse<YouTubeApiCaptionItem> = {
        kind: "youtube#captionListResponse",
        etag: "test-etag",
        items: [],
      };

      mockFetchApi.mockResolvedValueOnce(ok(emptyResponse));

      const result = await getTranscriptMetadata("test-video-id", mockApiKey);

      expect(result.isOk()).toBe(true);
      expect(result.isErr()).toBe(false);
      expect(result._unsafeUnwrap()).toStrictEqual([]);
    });

    test("異常系: fetchエラーの場合にエラーを返す", async () => {
      mockFetchApi.mockResolvedValueOnce(err(new Error("Captions API Error")));

      const result = await getTranscriptMetadata("test-video-id", mockApiKey);

      expect(result.isOk()).toBe(false);
      expect(result.isErr()).toBe(true);
      expect(result._unsafeUnwrapErr()).toStrictEqual(new Error("Captions API Error"));
    });
  });
});
